In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

#### load Data

In [3]:
orders = pd.read_excel(r"C:\Users\hp\OneDrive\Desktop\Retail-Analytics-Platform\Data\raw.xlsx",sheet_name="Orders")
returns = pd.read_excel(r"C:\Users\hp\OneDrive\Desktop\Retail-Analytics-Platform\Data\raw.xlsx",sheet_name="Returns")
people = pd.read_excel(r"C:\Users\hp\OneDrive\Desktop\Retail-Analytics-Platform\Data\raw.xlsx",sheet_name="People")

In [4]:
df1 = orders.copy()

In [5]:
df1.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,Oklahoma,United States,Central US,USCA,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,New South Wales,Australia,Oceania,Asia Pacific,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,Queensland,Australia,Oceania,Asia Pacific,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,Berlin,Germany,Western Europe,Europe,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,Dakar,Senegal,Western Africa,Africa,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [6]:
df1.duplicated().sum() #no duplicate removing

np.int64(0)

In [7]:
missing = (df1.isnull().sum().to_frame("Missing Values"))
missing["Percentage"] = (missing["Missing Values"] /len(df1)) * 100
missing.sort_values(by="Percentage",ascending=False)

                Missing Values  Percentage
Postal Code              41296    80.51472
Row ID                       0     0.00000
Order Date                   0     0.00000
Order ID                     0     0.00000
Ship Mode                    0     0.00000
Customer ID                  0     0.00000
Customer Name                0     0.00000
Ship Date                    0     0.00000
Segment                      0     0.00000
City                         0     0.00000
State                        0     0.00000
Country                      0     0.00000
Region                       0     0.00000
Market                       0     0.00000
Product ID                   0     0.00000
Category                     0     0.00000
Sub-Category                 0     0.00000
Product Name                 0     0.00000
Sales                        0     0.00000
Quantity                     0     0.00000
Discount                     0     0.00000
Profit                       0     0.00000
Shipping Cost                0     0.00000
Order Priority               0     0.00000

In [8]:
# Standardize Text
df1["Segment"].value_counts()

Segment
Consumer       26518
Corporate      15429
Home Office     9343
Name: count, dtype: int64

In [10]:
df1["Category"].value_counts()

Category
Office Supplies    31289
Technology         10141
Furniture           9860
Name: count, dtype: int64

In [11]:
df1["Ship Mode"].value_counts()

Ship Mode
Standard Class    30775
Second Class      10309
First Class        7505
Same Day           2701
Name: count, dtype: int64

In [12]:
df1["Market"].value_counts()

Market
Asia Pacific    14302
Europe          11729
USCA            10378
LATAM           10294
Africa           4587
Name: count, dtype: int64

In [13]:
df1.dtypes

Row ID                     int64
Order ID                     str
Order Date        datetime64[us]
Ship Date         datetime64[us]
Ship Mode                    str
Customer ID                  str
Customer Name                str
Segment                      str
Postal Code              float64
City                         str
State                        str
Country                      str
Region                       str
Market                       str
Product ID                   str
Category                     str
Sub-Category                 str
Product Name                 str
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority               str
dtype: object

In [14]:
invalid_dates = df1[df1["Ship Date"] <df1["Order Date"]]
len(invalid_dates)

0

In [15]:
df1[["Sales","Profit","Quantity","Shipping Cost"]].describe()

              Sales        Profit      Quantity  Shipping Cost
count  51290.000000  51290.000000  51290.000000   51290.000000
mean     246.490581     28.610982      3.476545      26.478567
std      487.565361    174.340972      2.278766      57.251373
min        0.444000  -6599.978000      1.000000       1.002000
25%       30.758625      0.000000      2.000000       2.610000
50%       85.053000      9.240000      3.000000       7.790000
75%      251.053200     36.810000      5.000000      24.450000
max    22638.480000   8399.976000     14.000000     933.570000

In [18]:
df1.to_excel(r"C:\Users\hp\OneDrive\Desktop\Retail-Analytics-Platform\Data\clean_raw.xlsx",index=False)